name: brick_app_v2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  settings_ui: ^2.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.9
  equatable: ^2.0.3
  dartz: ^0.10.1
  uri: ^1.0.0
  dio: ^4.0.6
  injectable: ^1.5.3
  get_it: ^7.2.0
  auto_route: ^3.2.4
  cached_network_image: ^3.2.0
  syncfusion_flutter_pdfviewer: ^20.4.44
  freezed_annotation: ^2.0.0
  json_annotation: ^4.4.0
  html: ^0.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.8
  mocktail: ^0.3.0
  http_mock_adapter: ^0.3.2
  bloc_test: ^9.0.3
  auto_route_generator: ^3.2.3
  fast_i18n: ^5.12.1
  freezed: ^2.0.0
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
